version: '3'
services:
  nmcd:
    container_name: nmcd
    build:
      context: ./nmcd
    volumes:
      - /home/hg/nmchain/:/home/nmcd/.namecoin
    environment:
      RPCUSER: rpcuser
      RPCPASSWORD: faklsdjfkas57823432fh
      RPCPORT: 8336
  ws:
    container_name: ws
    build:
      context: ./ws
    ports:
      - "80:8080"
    environment:
      RPCUSER: rpcuser
      RPCPASSWORD: faklsdjfkas57823432fh
      RPCPORT: 8336
